2024-12-27 14:12:47,492 - VideoFlow - INFO - logger.py:68 - Logger initialisé
2024-12-27 14:12:47,492 - VideoFlow.Main - INFO - main.py:15 - Démarrage de l'application
2024-12-27 14:12:47,578 - VideoFlow.MainWindow - INFO - main_window.py:11 - Initialisation de la fenêtre principale
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - INFO - plugin_manager.py:17 - PluginManager initialisé avec le dossier: /Users/nico/Documents/videoFlow/src/plugins
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:18 - Le dossier existe: True
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:21 - Contenu du dossier plugins:
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:30 -   - Fichier: __init__.py
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:25 -   - Dossier: tree_manager
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:26 -     Contenu:
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:25 -   - Dossier: duplicate_finder
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:26 -     Contenu:
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:28 -       - window.py
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:28 -       - video_hasher.py
2024-12-27 14:12:47,578 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:28 -       - __init__.py
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:28 -       - plugin.py
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:25 -   - Dossier: video_merger
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:26 -     Contenu:
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:25 -   - Dossier: regex_renamer
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:26 -     Contenu:
2024-12-27 14:12:47,579 - VideoFlow.MainWindow - DEBUG - main_window.py:16 - Initialisation de l'interface utilisateur
2024-12-27 14:12:47,579 - VideoFlow.MainWindow - DEBUG - main_window.py:26 - Chargement des plugins
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - INFO - plugin_manager.py:36 - Début du chargement des plugins
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:46 - Dossiers de plugins trouvés: ['tree_manager', 'duplicate_finder', 'video_merger', 'regex_renamer']
2024-12-27 14:12:47,579 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:53 - Vérification du dossier tree_manager:
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:54 -   - plugin.py existe: False
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:55 -   - __init__.py existe: False
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - WARNING - plugin_manager.py:64 - Fichiers manquants dans: /Users/nico/Documents/videoFlow/src/plugins/tree_manager
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - WARNING - plugin_manager.py:66 -   - plugin.py manquant
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - WARNING - plugin_manager.py:68 -   - __init__.py manquant
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:53 - Vérification du dossier duplicate_finder:
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:54 -   - plugin.py existe: True
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:55 -   - __init__.py existe: True
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:58 - Tentative de chargement du plugin depuis: /Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:84 - Chargement du plugin depuis: /Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py
2024-12-27 14:12:47,580 - VideoFlow.PluginManager - ERROR - plugin_manager.py:120 - Erreur lors du chargement du plugin /Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py: cannot import name 'Plugin' from 'src.plugins.duplicate_finder.plugin' (/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py)
Traceback (most recent call last):
  File "/Users/nico/Documents/videoFlow/src/core/plugin_manager.py", line 94, in _load_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py", line 6, in <module>
    from src.plugins.duplicate_finder.window import DuplicateFinderWindow
  File "/Users/nico/Documents/videoFlow/src/plugins/__init__.py", line 1, in <module>
    from . import duplicate_finder
  File "/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/__init__.py", line 1, in <module>
    from .plugin import Plugin
ImportError: cannot import name 'Plugin' from 'src.plugins.duplicate_finder.plugin' (/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py)
2024-12-27 14:12:47,583 - VideoFlow.PluginManager - ERROR - plugin_manager.py:62 - Erreur lors du chargement du plugin duplicate_finder: cannot import name 'Plugin' from 'src.plugins.duplicate_finder.plugin' (/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py)
Traceback (most recent call last):
  File "/Users/nico/Documents/videoFlow/src/core/plugin_manager.py", line 60, in load_plugins
    self._load_plugin(plugin_file, plugin_folder)
  File "/Users/nico/Documents/videoFlow/src/core/plugin_manager.py", line 94, in _load_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py", line 6, in <module>
    from src.plugins.duplicate_finder.window import DuplicateFinderWindow
  File "/Users/nico/Documents/videoFlow/src/plugins/__init__.py", line 1, in <module>
    from . import duplicate_finder
  File "/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/__init__.py", line 1, in <module>
    from .plugin import Plugin
ImportError: cannot import name 'Plugin' from 'src.plugins.duplicate_finder.plugin' (/Users/nico/Documents/videoFlow/src/plugins/duplicate_finder/plugin.py)
2024-12-27 14:12:47,583 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:53 - Vérification du dossier video_merger:
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:54 -   - plugin.py existe: False
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:55 -   - __init__.py existe: False
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:64 - Fichiers manquants dans: /Users/nico/Documents/videoFlow/src/plugins/video_merger
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:66 -   - plugin.py manquant
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:68 -   - __init__.py manquant
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:53 - Vérification du dossier regex_renamer:
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:54 -   - plugin.py existe: False
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:55 -   - __init__.py existe: False
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:64 - Fichiers manquants dans: /Users/nico/Documents/videoFlow/src/plugins/regex_renamer
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:66 -   - plugin.py manquant
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - WARNING - plugin_manager.py:68 -   - __init__.py manquant
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - INFO - plugin_manager.py:70 - Plugins chargés: []
2024-12-27 14:12:47,584 - VideoFlow.PluginManager - DEBUG - plugin_manager.py:125 - Retourne 0 plugins
2024-12-27 14:12:47,584 - VideoFlow.MainWindow - INFO - main_window.py:29 - Nombre de plugins chargés: 0
2024-12-27 14:12:47,584 - VideoFlow.MainWindow - DEBUG - main_window.py:36 - Disposition: 0 lignes x 2 colonnes pour 0 plugins
2024-12-27 14:12:47,584 - VideoFlow.MainWindow - DEBUG - main_window.py:58 - Dimensions de la fenêtre: 450x30
2024-12-27 14:12:47,584 - VideoFlow.MainWindow - INFO - main_window.py:62 - Interface utilisateur initialisée
2024-12-27 14:12:47,613 - VideoFlow.Main - INFO - main.py:20 - Fenêtre principale affichée
